### PR TITLE
Feat/Switch Spartan Backend to Use Goldilocks Field

### PR DESCRIPTION
**Pull request by darth-cy**
Completed in this PR:
- Removed `ristretto255` scalar field definition. Use new `goldilocks` `Scalar` impl.
- Remove elliptic group definition.
- All curve pairing-based PCS code sections removed.
- Add degree 2 extension field to Goldilocks using the `ceno-goldilocks` repo.
- Convert all structs with hard-coded `Scalar` field struct to a generic.
- All `Scalar` operations and checks will be preserved.

Scalar Checks Debugging progress:
[Done] `ProductCircuitEvalProofBatched` -> `fn verify`: 1 check
[Done] `HashLayerProof` -> `fn verify_helper`: 4 checks
[Done] `HashLayerProof` -> `fn verify`: 1 check

### CODE REVIEW

**Review by matthiasgoergens — DISMISSED** [review]

**Comment by matthiasgoergens** [comment]
Please see https://github.com/scroll-tech/ceno-recursion/pull/35 for an attempt at resolving the conflicts.

File: spartan_parallel/examples/mem.rs
Comment (kunxian-xia) [inline spartan_parallel/examples/mem.rs:1]: why are these files deleted?

**Review by matthiasgoergens — COMMENTED** [review]
Just trying to remove my 'requested changes' tag.

File: spartan_parallel/Cargo.toml [hunk 1]
```diff
@@ -25,9 +25,11 @@ serde = { version = "1", features = ["derive"], default-features = false }
 bincode = { version = "1", default-features = false }
 subtle = { version = "2", features = ["i128"], default-features = false }
 zeroize = { version = "1", default-features = false, features = ["alloc"] }
-itertools = { version = "0.13", default-features = false }
+itertools = { version = "0.10", default-features = false }
 colored = { version = "2", default-features = false, optional = true }
 flate2 = { version = "1" }
+ceno-goldilocks = { git = "https://github.com/scroll-tech/ceno-Goldilocks.git", branch = "fix/crate-ready" }
```
Comment (matthiasgoergens) [inline spartan_parallel/Cargo.toml:31]: You should be able to just contribute your fix the main branch of that repository?  Let me have a look.

Comment (darth-cy) [reply spartan_parallel/Cargo.toml:31]: I generally don't push to `main` without PR review, so here's one created: https://github.com/scroll-tech/ceno-Goldilocks/pull/2

File: spartan_parallel/src/scalar/goldilocks.rs [hunk 2]
```diff
@@ -0,0 +1,716 @@
+//! This module provides an implementation of the Goldilocks scalar field
```
[the remark this answers is not in the document]
Comment (darth-cy) [reply spartan_parallel/src/scalar/goldilocks.rs]: Using `ceno-goldilocks` as dependency now as requested.

File: circ_blocks/examples/zxc.rs [hunk 3]
```diff
@@ -23,15 +24,16 @@ use circ::cfg::{
...
 
 use libspartan::{
-    instance::Instance, Assignment, InputsAssignment, MemsAssignment, SNARKGens, VarsAssignment,
-    SNARK,
+    instance::Instance, Assignment, InputsAssignment, MemsAssignment, VarsAssignment, SNARK,
 };
 use merlin::Transcript;
 use serde::{Deserialize, Serialize};
 use std::time::*;
+use std::time::*;
```
Comment (matthiasgoergens) [inline circ_blocks/examples/zxc.rs:36]: Looks like we should do quite a bit of clean up?  This is just a duplicate of the line above.

File: spartan_parallel/Cargo.toml (hunk 1 above)
Comment (matthiasgoergens) [reply spartan_parallel/Cargo.toml:31]: Yes, I meant create a PR etc. :)  Thanks!

File: circ_blocks/examples/zxc.rs (hunk 3 above)
Comment (darth-cy) [reply circ_blocks/examples/zxc.rs:36]: Yes you're right. This is from the merge conflict resolution. While I deleted a bunch of them, some might still slip through. I'm cleaning these up

Comment (matthiasgoergens) [reply circ_blocks/examples/zxc.rs:36]: Have a look at https://github.com/scroll-tech/ceno-recursion/pull/46 for some automated cleanup I did.  I think that fixes most of these and makes the diff a bit smaller.

Comment (matthiasgoergens) [reply circ_blocks/examples/zxc.rs:36]: Basically what I did for https://github.com/scroll-tech/ceno-recursion/pull/46 was:

Apply Ceno's formatting rules against `main` and make a separate PR for that.

Apply Ceno's formatting rules against the changes in your Goldilocks PR here, and make a PR for that.

File: spartan_parallel/src/scalar/fp.rs [hunk 4]
```diff
@@ -0,0 +1,204 @@
...
+use rand::{CryptoRng, RngCore};
+use serde::{Deserialize, Serialize};
+use std::ops::Neg;
+use subtle::{Choice, ConditionallySelectable, ConstantTimeEq, CtOption};
+use zeroize::Zeroize;
+
+/// Constant representing the modulus
+/// q = 2^64 - 2^32 + 1
+/// 0xFFFFFFFF00000001
+const P: u64 = 0xFFFF_FFFF_0000_0001;
```
Comment (matthiasgoergens) [inline spartan_parallel/src/scalar/fp.rs:17]: Please take this from the Goldilocks crate.

File: spartan_parallel/src/scalar/fp.rs [hunk 5]
```diff
@@ -0,0 +1,204 @@
...
+    transcript.append_scalar(label, &input);
+  }
+
+  /// Append a vector Goldilocks scalars to transcript
+  fn append_field_vector_to_transcript(
+    label: &'static [u8],
+    transcript: &mut Transcript,
+    input: &[Self],
+  ) {
+    transcript.append_message(label, b"begin_append_vector");
```
Comment (matthiasgoergens) [inline spartan_parallel/src/scalar/fp.rs:80]: Why do we need these messages?  Who's supposed to read them?

File: spartan_parallel/src/scalar/fp.rs [hunk 6]
```diff
@@ -0,0 +1,204 @@
...
+  }
+
+  /// Returns one, the multiplicative identity.
+  #[inline]
+  pub const fn one() -> Self {
+    Self(Goldilocks(1u64))
+  }
+}
+
+impl<'a, 'b> Add<&'b Scalar> for &'a Scalar {
```
Comment (matthiasgoergens) [inline spartan_parallel/src/scalar/fp.rs:153]: Consider using a macro to generate all the instances here for Add, Sub and Mul (and the `AddAssign` etc variants, and for the references).

Doing it manually, I can tell you that you forgot some.

File: spartan_parallel/src/scalar/fp.rs [hunk 7]
```diff
@@ -0,0 +1,204 @@
...
+impl<'a, 'b> Mul<&'b Scalar> for &'a Scalar {
+  type Output = Scalar;
+
+  #[inline]
+  fn mul(self, rhs: &'b Scalar) -> Scalar {
+    self.inner().mul(rhs.inner()).into()
+  }
+}
+
+impl<T> Sum<T> for Scalar
```
Comment (matthiasgoergens) [inline spartan_parallel/src/scalar/fp.rs:180]: I think you can take this from the goldilocks crate.  Same for Product.

File: spartan_parallel/src/scalar/fp.rs [hunk 8]
```diff
@@ -0,0 +1,204 @@
...
+impl Neg for Scalar {
+  type Output = Scalar;
+
+  #[inline]
+  fn neg(self) -> Scalar {
+    self.0.neg().into()
+  }
+}
+impl Default for Scalar {
+  #[inline]
```
Comment (matthiasgoergens) [inline spartan_parallel/src/scalar/fp.rs:129]: Don't bother with `inline` annotations.  The compiler is generally smart enough to figure that out by itself.  Especially with LTO and PGO.

File: spartan_parallel/src/scalar/fp.rs [hunk 9]
```diff
@@ -0,0 +1,204 @@
...
+
+  fn field_zero() -> Self {
+    Goldilocks::ZERO.into()
+  }
+
+  fn field_one() -> Self {
+    Goldilocks::ONE.into()
+  }
+
+  fn random<Rng: RngCore + CryptoRng>(rng: &mut Rng) -> Self {
```
Comment (matthiasgoergens) [inline spartan_parallel/src/scalar/fp.rs:38]: I think you can take that from the Goldilocks crate.  (If not, please add it there, and then take it from there.)

File: spartan_parallel/src/lib.rs [hunk 10]
```diff
@@ -74,29 +65,29 @@ const W3_WIDTH: usize = 8;
...
 #[derive(Clone, Serialize, Deserialize)]
-pub struct Assignment {
+pub struct Assignment<S: SpartanExtensionField> {
   /// Entries of an assignment
-  pub assignment: Vec<Scalar>,
+  pub assignment: Vec<S>,
 }
 
-impl Assignment {
+impl<S: SpartanExtensionField> Assignment<S> {
```
Comment (matthiasgoergens) [inline spartan_parallel/src/lib.rs:84]: Again: if you rename `S` to be `Scalar` (in most places) it will make your diff so much smaller and easier to review.

File: spartan_parallel/src/lib.rs [hunk 11]
```diff
@@ -135,93 +126,57 @@ fn write_bytes(mut f: &File, bytes: &[u8; 32]) -> std::io::Result<()> {
   for i in 0..size {
     write!(&mut f, "{} ", bytes[i])?;
   }
-  writeln!(&mut f)?;
+  writeln!(&mut f, "")?;
```
Comment (matthiasgoergens) [inline spartan_parallel/src/lib.rs:129]: Please leave as is.

File: spartan_parallel/src/lib.rs [hunk 12]
```diff
@@ -118,9 +109,9 @@ impl Assignment {
   }
 
   /// Write the assignment into a file
-  pub fn write(&self, f: &File) -> std::io::Result<()> {
+  pub fn write(&self, mut f: &File) -> std::io::Result<()> {
     for assg in &self.assignment {
-      write_bytes(f, &assg.to_bytes())?;
+      write_bytes(&mut f, &assg.to_bytes())?;
```
Comment (matthiasgoergens) [inline spartan_parallel/src/lib.rs:114]: Why did this have to change?

File: spartan_parallel/src/lib.rs [hunk 13]
```diff
@@ -321,15 +279,14 @@ impl IOProofs {
...
       if input_liveness[i] {
-        live_input.push(input[i]);
+        live_input.push(input[i].clone());
       }
     }
     input_indices = input_indices[..live_input.len()].to_vec();
 
     // batch verify all proofs
-    PolyEvalProof::verify_plain_batched_points(
+    let _ = PolyEvalProof::verify_plain_batched_points(
```
Comment (matthiasgoergens) [inline spartan_parallel/src/lib.rs:288]: Please leave as is.

File: spartan_parallel/src/sumcheck.rs [hunk 14]
```diff
@@ -72,89 +71,43 @@ impl SumcheckInstanceProof {
 }
 
 #[derive(Serialize, Deserialize, Debug)]
-pub struct ZKSumcheckInstanceProof {
-  comm_polys: Vec<CompressedGroup>,
-  comm_evals: Vec<CompressedGroup>,
-  proofs: Vec<DotProductProof>,
+pub struct ZKSumcheckInstanceProof<S: SpartanExtensionField> {
+  proofs: Vec<DotProductProof<S>>,
 }
```
Comment (kunxian-xia) [inline spartan_parallel/src/sumcheck.rs:76]: In our usage of spartan, we don't care about zero knowledge property. Moreover, it's also difficult to build zero knowledge sumcheck protocol based on hash function. Therefore, we can get rid of (i.e. remove) types like `ZKSumcheckInstanceProof` and only keep `SumcheckInstanceProof`.

File: spartan_parallel/src/lib.rs (hunk 13 above)
Comment (darth-cy) [reply spartan_parallel/src/lib.rs]: Modified as suggested.

File: spartan_parallel/src/scalar/fp.rs (hunk 8 above)
Comment (darth-cy) [reply spartan_parallel/src/scalar/fp.rs]: Removed `inline` annotation from `scalar` mod.

File: spartan_parallel/src/lib.rs (hunk 12 above)
Comment (darth-cy) [reply spartan_parallel/src/lib.rs]: Modified to original as requested.

File: spartan_parallel/src/scalar/fp.rs (hunk 5 above)
Comment (matthiasgoergens) [reply spartan_parallel/src/scalar/fp.rs:80]: Ok. I'm just asking because it looked like new code.

You don't have to change the original code base here, the PR is already but enough. Thanks.

Comment (darth-cy) [reply spartan_parallel/src/scalar/fp.rs:80]: Ah ok. Marked as resolved

**Comment by yczhangsjtu** [comment]
I'm a bit concerned about eliminating all the function parameters related to commitments because, well, we'll have to add them back in later. I see the codebase provides a trait for commitment scheme, and a mock implementation for this trait. Isn't it simpler to just switching to the mock implementation?

**Comment by darth-cy** [comment]
> I'm a bit concerned about eliminating all the function parameters and struct fields related to commitments because, well, we'll have to add them back in later when we connect it to our own PCS. I see the codebase provides a trait for commitment scheme, and a mock implementation for this trait. Isn't it simpler to just switching to the mock implementation, and only deleting the ECC-based implementations?

The mock commitment seems to still be based on pairing. Notably there's a trait bound `JoltField` on mock commitment's internal `DensePolynomial<F>`. Is this trait bound compatible with Goldilocks? As a side note, it seems sub-directory `commitment` is not included and doesn't compile as of now. The spec for `JoltField` is oddly not found

**Comment by yczhangsjtu** [comment]
> > I'm a bit concerned about eliminating all the function parameters and struct fields related to commitments because, well, we'll have to add them back in later when we connect it to our own PCS. I see the codebase provides a trait for commitment scheme, and a mock implementation for this trait. Isn't it simpler to just switching to the mock implementation, and only deleting the ECC-based implementations?
> 
> The mock commitment seems to still be based on pairing. Notably there's a trait bound `JoltField` on mock commitment's internal `DensePolynomial<F>`. Is this trait bound compatible with Goldilocks? As a side note, it seems sub-directory `commitment` is not included and doesn't compile as of now. The spec for `JoltField` is oddly not found. I'm suspecting this folder is copied from some other repo and not originally from `Spartan`?

I see. The commitment scheme trait isn't actually used at all.

File: spartan_parallel/Cargo.toml (hunk 1 above)
Comment (kunxian-xia) [reply spartan_parallel/Cargo.toml:31]: Why do you prefer to import `goldilocks` crate as `ceno-goldilocks`?

File: spartan_parallel/examples/interface.rs [hunk 15]
```diff
@@ -5,9 +5,8 @@ use std::io::{BufRead, Read};
 use std::{default, env};
 use std::{fs::File, io::BufReader};
 
-use libspartan::{
-  instance::Instance, InputsAssignment, MemsAssignment, SNARKGens, VarsAssignment, SNARK,
-};
+use libspartan::scalar::{Scalar, SpartanExtensionField};
```
Comment (kunxian-xia) [inline spartan_parallel/examples/interface.rs:8]: It makes more sense to import `ScalarExt2` instead of `Scalar` here as `Scalar` does not provide enough soundness for us.

File: spartan_parallel/src/scalar/mod.rs [hunk 16]
```diff
@@ -1,43 +1,325 @@
...
+  + Sum
+  + Product
+  + Clone
+  + Serialize
+  + Hash
+  + From<Self::InnerType>
+  + fmt::Debug
+{
+  /// Inner Goldilocks extension field
+  type InnerType: ExtensionField + Field;
```
Comment (kunxian-xia) [inline spartan_parallel/src/scalar/mod.rs:47]: It's pretty cumbersome to access its base field via `<S::InnerType as ExtensionField>::BaseField`, right?

Comment (kunxian-xia) [reply spartan_parallel/src/scalar/mod.rs:47]: We need to use BaseField in a lot of places for performance. For example, the type of each cell's value in the R1CS matrices must belong to the base field.

File: spartan_parallel/src/sparse_mlpoly.rs [hunk 17]
```diff
@@ -1,98 +1,89 @@
...
 use merlin::Transcript;
 use serde::{Deserialize, Serialize};
 
 #[derive(Clone, Debug, Serialize, Deserialize)]
-pub struct SparseMatEntry {
+pub struct SparseMatEntry<S: SpartanExtensionField> {
   row: usize,
   col: usize,
-  val: Scalar,
+  val: S,
```
Comment (kunxian-xia) [inline spartan_parallel/src/sparse_mlpoly.rs:22]: If `S` itself extends the `ExtensionField` trait, then val's type should be `S::BaseField`. Otherwise, we need to use this cumbersome expression `<S::InnerType as ExtensionField>::BaseField`.

File: spartan_parallel/Cargo.toml (hunk 1 above)
Comment (darth-cy) [reply spartan_parallel/Cargo.toml:31]: I tried to import the main branch again, but I kept getting this error:
```
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /Users/raygao/.cargo/git/checkouts/ceno-goldilocks-e1f7db6a8c06e8fe/29a15d1/src/lib.rs:4:1
  |
4 | #![feature(generic_const_exprs)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `goldilocks` (lib) due to 1 previous error
```

I thought it's because of toolchain versioning issue but after merging in the toolchain fix this error still occurs.

Comment (darth-cy) [reply spartan_parallel/Cargo.toml]: Fixed. Now importing main branch of `ceno-goldilocks` as `goldilocks`.

File: spartan_parallel/src/sparse_mlpoly.rs [hunk 18]
```diff
@@ -564,62 +494,60 @@ impl MultiSparseMatPolynomialAsDense {
...
   ) {
     let (r_hash, r_multiset_check) = r_mem_check;
 
     //hash(addr, val, ts) = ts * r_hash_sqr + val * r_hash + addr
-    let r_hash_sqr = r_hash * r_hash;
-    let hash_func = |addr: &Scalar, val: &Scalar, ts: &Scalar| -> Scalar {
-      ts * r_hash_sqr + val * r_hash + addr
-    };
+    let r_hash_sqr = *r_hash * *r_hash;
+    let hash_func = |addr: &S, val: &S, ts: &S| -> S { *ts * r_hash_sqr + *val * *r_hash + *addr };
```
Comment (kunxian-xia) [inline spartan_parallel/src/sparse_mlpoly.rs:527]: This closure can be boosted by by changing the type of `addr, ts` from `S` to `S::BaseField` as extension field element multiply by base field element `e*b` (https://github.com/scroll-tech/ceno-Goldilocks/blob/master/src/extfield.rs#L24) is much faster than `e * e`

File: spartan_parallel/src/scalar/fp.rs (hunk 9 above)
Comment (darth-cy) [reply spartan_parallel/src/scalar/fp.rs:33]: Updated.

File: spartan_parallel/examples/interface.rs (hunk 15 above)
Comment (darth-cy) [reply spartan_parallel/examples/interface.rs]: Changed to `ScalarExt2` as requested

File: circ_blocks/examples/zxc.rs [hunk 19]
```diff
@@ -12,6 +12,7 @@ use circ::target::r1cs::wit_comp::StagedWitCompEvaluator;
 use circ::target::r1cs::ProverData;
 use circ::target::r1cs::{Lc, VarType};
 use core::cmp::min;
+use libspartan::scalar::{Scalar, SpartanExtensionField};
```
[the remark this answers is not in the document]
Comment (darth-cy) [reply circ_blocks/examples/zxc.rs]: Changed to `ScalarExt2` as requested

File: spartan_parallel/src/scalar/mod.rs [hunk 20]
```diff
@@ -42,10 +42,15 @@ pub trait SpartanExtensionField:
...
   + From<Self::InnerType>
   + fmt::Debug
+  + Mul<Self::BaseField, Output = Self>
+  + MulAssign<Self::BaseField>
 {
   /// Inner Goldilocks extension field
   type InnerType: ExtensionField + Field;
 
+  /// Basefield for conserving computational resources
+  type BaseField: SpartanExtensionField;
```
Comment (kunxian-xia) [inline spartan_parallel/src/scalar/mod.rs:52]: `BaseField` itself is not `SpartanExtensionField`. why not use `type BaseField: Field`?

**Comment by kunxian-xia** [comment]
The features not included in this pr are tracked below
- [ ] #49 
- [ ] #50

File: spartan_parallel/src/scalar/mod.rs (hunk 20 above)
Comment (darth-cy) [reply spartan_parallel/src/scalar/mod.rs]: You're right. This is corrected.

File: spartan_parallel/src/scalar/mod.rs
Comment (matthiasgoergens) [inline spartan_parallel/src/scalar/mod.rs:1]: Why do we re-implement the field arithmetic here?  What's the reason we can't re-use ceno-goldilocks or Plonky2 or so?

File: spartan_parallel/src/sparse_mlpoly.rs [hunk 21]
```diff
@@ -404,30 +333,34 @@ impl SparseMatPolynomial {
...
     let comb_ops = DensePolynomial::merge(
       row
         .ops_addr
-        .iter()
-        .chain(row.read_ts.iter())
-        .chain(col.ops_addr.iter())
-        .chain(col.read_ts.iter())
-        .chain(val_vec.iter()),
+        .into_iter()
+        .chain(row.read_ts.into_iter())
```
Comment (matthiasgoergens) [inline spartan_parallel/src/sparse_mlpoly.rs:345]: Itertool's `chain` macro is a bit easier to read, IHMO.  But that doesn't have to be in this PR.

File: spartan_parallel/src/sparse_mlpoly.rs [hunk 22]
```diff
@@ -436,25 +369,21 @@ impl SparseMatPolynomial {
         let row = self.M[i].row;
         let col = self.M[i].col;
         let val = &self.M[i].val;
-        eval_table_rx[row] * eval_table_ry[col] * val
+        eval_table_rx[row] * eval_table_ry[col] * *val
```
Comment (matthiasgoergens) [inline spartan_parallel/src/sparse_mlpoly.rs:372]: If we are implementing our own field element arithmetic anyway, we can add instances for arithmetic with references, too.  See how we do that in Ceno.

(We don't need to do that in this PR.)

File: spartan_parallel/src/sparse_mlpoly.rs [hunk 23]
```diff
@@ -478,34 +407,29 @@ impl SparseMatPolynomial {
...
         let row = self.M[i].row;
         let col = self.M[i].col;
         let val = &self.M[i].val;
-        (row, val * z[col / max_num_cols][col % max_num_cols])
+        (row, *val * z[col / max_num_cols][col % max_num_cols])
       })
-      .fold(vec![Scalar::zero(); num_rows], |mut Mz, (r, v)| {
-        Mz[r] += v;
+      .fold(vec![S::field_zero(); num_rows], |mut Mz, (r, v)| {
+        Mz[r] = Mz[r] + v;
```
Comment (matthiasgoergens) [inline spartan_parallel/src/sparse_mlpoly.rs:420]: We can implement AddAssign?

File: spartan_parallel/src/sparse_mlpoly.rs [hunk 24]
```diff
@@ -478,34 +407,29 @@ impl SparseMatPolynomial {
...
+  pub fn compute_eval_table_sparse(&self, rx: &[S], num_rows: usize, num_cols: usize) -> Vec<S> {
     assert_eq!(rx.len(), num_rows);
 
-    let mut M_evals: Vec<Scalar> = vec![Scalar::zero(); num_cols];
+    let mut M_evals: Vec<S> = vec![S::field_zero(); num_cols];
 
     for i in 0..self.M.len() {
       let entry = &self.M[i];
-      M_evals[entry.col] += rx[entry.row] * entry.val;
+      M_evals[entry.col] = M_evals[entry.col] + rx[entry.row] * entry.val;
```
Comment (matthiasgoergens) [inline spartan_parallel/src/sparse_mlpoly.rs:432]: Why don't we implement AddAssign?

File: spartan_parallel/src/sparse_mlpoly.rs [hunk 25]
```diff
@@ -1,98 +1,89 @@
...
+  pub fn new(row_ops_val: Vec<DensePolynomial<S>>, col_ops_val: Vec<DensePolynomial<S>>) -> Self {
     assert_eq!(row_ops_val.len(), col_ops_val.len());
 
+    let ret_row_ops_val = row_ops_val.clone();
+    let ret_col_ops_val = col_ops_val.clone();
+
     let derefs = {
       // combine all polynomials into a single polynomial (used below to produce a single commitment)
-      let comb = DensePolynomial::merge(row_ops_val.iter().chain(col_ops_val.iter()));
+      let comb = DensePolynomial::merge(row_ops_val.into_iter().chain(col_ops_val.into_iter()));
```
Comment (matthiasgoergens) [inline spartan_parallel/src/sparse_mlpoly.rs:53]: You could just clone here, then you don't need to change all the other lines.  Makes the diff easier to review.

**Review by matthiasgoergens — COMMENTED** [review]
Just looking through this briefly and got some questions.  Not a full review.  (And you can merge without addressing my questions / comments.  I'm just curious.)
